name: pub_upgrader
description: A command-line that upgrade all dependencies in your pubspec.yaml file to the latest version.
version: 1.0.0
repository: https://github.com/callmephil/pub_upgrader
issue_tracker: https://github.com/callmephil/pub_upgrader/issues

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
